# Setup
title:               Iosif Vilcea
tagline:             
description:          
url:                 https://www.iosifvilcea.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Iosif Vilcea
  url:               https://x.com/iosifvilcea
  email:             contact@iosifvilcea.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
